### ISSUE TITLE
Complete All Features of Spec Editor

### ISSUE THREAD

**Issue by agilgur5** [LTLMoP/LTLMoPWeb3D#36]
E.g. Config Editor, View Automaton, Visualize Counterstrategy, Workspace Decomp, LTL Output. Line number highlighting w/ analyze would be nice and so would syntax highlighting.

**Comment by agilgur5** [comment]
- [x] LTL Output complete: #39.
- [x] File extensions are now specified by default: #48

**Comment by agilgur5** [comment]
Updated tasks in order of priority: 
1. [ ] Visualize Counterstrategy: #40 
1. [x] ~Workspace Decomp~: #58
1. [ ] View Automaton: #51
1. [x] ~Syntax Highlighting~: #38
2. [ ] Analyze Line Number Highlighting
1. [ ] Config Editor

**Comment by agilgur5** [comment]
1. [x] Workspace Decomposition complete: #58 

 leftover tasks:
1. [ ] Visualize Counterstategy (working on furiously): #40 
1. [ ] View Automaton: #51
1. [x] ~Syntax Highlighting~: #38
1. [ ] Line Numbers
1. [ ] Analyze Line Number Highlighting
1. [ ] Config Editor

**Comment by agilgur5** [comment]
1. [x] Syntax Highlighting complete: #38

leftover tasks:
1. [ ] Visualize Counterstrategy: #40
1. [ ] View Automaton: #51 
1. [ ] Line Numbers
1. [ ] Analyze Line Number Highlighting
1. [ ] Config Editor
